Evaluation/Controllers/DeptHeadController.cs
using Evaluation.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Evaluation.Controllers
{
    public class DeptHeadController : Controller
    {
        private EvaluationDB db = new EvaluationDB();
        // GET: DeptHead
        public ActionResult getEvaluations(string teachername)
        {

            if (teachername == null)
            {
                return View("Error");
            }

            // request a complete evaluation form based on teacherID
           
            

            List<Evaluation.Models.Evaluation> eval = db.Evaluations.Where(x => x.Teacher.Name== teachername).ToList();
            foreach( var item in eval)
            {
                Teacher teacher = db.Teachers.Where(m => m.Name == teachername).FirstOrDefault();
                item.Teacher = teacher;
                Student student = db.Students.Where(m => m.StudentID == item.StudentID).FirstOrDefault();
                item.Student= student;

            }
            if (eval == null)
            {
                return View("Error");
            }
            return View(eval);
        }

        public ActionResult findEvaluation(User user)
        {
            if (user.status == "department")
            {
                return View();
            }
            return RedirectToAction("../Login/Login");
        }


    }
}

Evaluation/Controllers/LoginController.cs
using Evaluation.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Evaluation.Controllers
{
    public class LoginController : Controller
    {
        private EvaluationDB db = new EvaluationDB();
        User user = new User();
        // GET: Login
        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(string username, string password)
        {
            user.username = username;
            user.password = password;

            User person = db.Users.Where(m => m.username == username).FirstOrDefault();
            if (person != null)
            {
                if (username == person.username)
                {
                    if (password == person.password)
                    {
                        if (person.status == "teacher")
                        {

                            Teacher teacher = db.Teachers.Where(m => m.username == user.username).FirstOrDefault();
                            TempData["teacherName"] = teacher.Name;
                            List<int> stList = db.Evaluations.Where(m => m.TeacherID == teacher.TeacherID).Select(m => m.StudentID).ToList();
                            ViewBag.Studlist = new SelectList(stList);
                            return View("../Teacher/index", person);

                        }
                    }

                    else return View("Unauthorized");
                }

                if (username == person.username)
                {
                    if (password == person.password)
                    {
                        if (person.status == "student")
                        {
                            Student stud = db.Students.Where(m => m.username == user.username).FirstOrDefault();
                            @TempData["studentId"] = stud.StudentID;
                            @TempData["studentName"] = stud.Name;
                            List<string> teachList = db.Teachers.Select(m => m.Name).ToList();
                            ViewBag.Teachlist = new SelectList(teachList);


                            return View("../Student/Index", person);
                        }



                    }
                    else return View("Unauthorized");
                }
                if (username == person.username)
                {
                    if (password == person.password)
                    {
                        if (person.status == "department")
                        {
                            List<string> teachList = db.Teachers.Select(m => m.Name).ToList();
                            ViewBag.Teachlist = new SelectList(teachList);
                            return View("../DeptHead/findEvaluation", person);
                        }


                    }
                    else return View("Unauthorized");
                }
                return View();
            }

            return View("Unauthorized"); ;


        }
    }
}

Evaluation/Views/Shared/Submitted.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Submitted</title>
</head>
<body>
    <br />
    <br />
    <br />
    <br />
    <hgroup>
        <h1>Evaluation Form Submitted.</h1>
        <h2>You have completed the evaluation.</h2>
    </hgroup>
    <p>
        <a href="~/Login">Back to Login Page</a>
    </p>
</body>
</html>

Evaluation/Views/Shared/Unauthorized.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Unauthorized</title>
</head>
<body>
    <br />
    <br />
    <hgroup>
        <h1>UnAuthorized.</h1>
        <h2>You are not Authorized to complete this request.</h2>
    </hgroup>
    <p>
        <a href="~/Login">Back to Login Page</a>
    </p>
</body>
</html>

Evaluation/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Evaluation APP</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>


<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Evaluation Form", "Login", "Login", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Student", "Index", "Student")</li>
                    <li>@Html.ActionLink("Teacher", "Index", "Teacher")</li>
                    <li>@Html.ActionLink("Department", "findEvaluation", "DeptHead")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Evaluation Form</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>
<style>
    body {
        background-image: url('../../Content/Saint-Martins-University.jpg');
        background-repeat: no-repeat;
        background-position: Top;
        align-content:center;
    }
</style>